# SVD analysis run for the AdamW baseline.
seed: 42
experiment_name: omat24_baseline_svd
task: omat24

dataset:
  root: data/rattled-300-subsampled
  target_key: energy_corrected_mp2020
  normalize_per_atom: true
  batch_size: 64
  num_workers: 0
  pin_memory: true
  radius: 6.0
  max_neighbors: 32
  split_fraction:
    train: 0.8
    val: 0.1
    test: 0.1
  max_samples: 20000
  split_seed: 1234

model:
  name: gemnet_oc_v2
  hidden_dim: 256
  depth: 6

train:
  epochs: 40

optim:
  use_muon: false
  adamw_lr: 0.002
  adamw_wd: 0.01
  grad_clip: 1.0

log:
  backend: wandb
  project: muon-fairchem
  csv_path: results/metrics_svd.csv
  log_interval: 50
  eval_interval: 1
  svd_interval: 1000 # Save SVD snapshots every 1000 steps
  svd_layers:
    - "backbone.blocks.0.atom_wise.grid_mlp.0.weight"
    - "backbone.blocks.1.atom_wise.grid_mlp.0.weight"
    - "backbone.blocks.2.atom_wise.grid_mlp.0.weight"
    - "backbone.blocks.3.atom_wise.grid_mlp.0.weight"
    - "backbone.blocks.4.atom_wise.grid_mlp.0.weight"
    - "backbone.blocks.5.atom_wise.grid_mlp.0.weight"

checkpoint:
  save_dir: results/checkpoints_baseline_svd
  monitor: val/mae
  mode: min
