experiment_name: omat24_baseline_svd
seed: 42

dataset:
  name: OMat24
  split: rattled-300-subsampled
  batch_size: 32
  num_workers: 0        # IMPORTANT due to memory constraints
  pin_memory: false

model:
  name: gemnet_oc_v2
  hidden_dim: 128
  depth: 6

optim:
  use_muon: false       # AdamW on all
  adamw_lr: 2.0e-3
  adamw_wd: 1.0e-2
  grad_clip: 0.0
  apply_layers: all     # ignored when use_muon: false

train:
  epochs: 40

log:
  log_interval: 50
  eval_interval: 1
  csv_path: results/metrics.csv
  svd_interval: 1000      # snapshot every ~1k steps (tune if your steps/epoch are small)
  svd_layers:
    - backbone.blocks.0.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.1.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.2.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.3.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.4.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.5.edge_wise.so2_conv_1.fc_m0.weight

checkpoint:
  save_dir: results/checkpoints_baseline
  monitor: val_mae
  mode: min
