experiment_name: omat24_muon_firstk_svd
seed: 42

dataset:
  root: data/rattled-300-subsampled
  name: OMat24
  split: rattled-300-subsampled
  batch_size: 32
  num_workers: 0
  pin_memory: false

model:
  name: gemnet_oc_v2
  hidden_dim: 128
  depth: 6

optim:
  use_muon: true
  # Muon hyperparams (match prior best where possible)
  muon_lr: 2.0e-3
  muon_wd: 0.0
  muon_eps: 1.0e-8
  muon_momentum: 0.9
  ortho: true
  # AdamW for the rest
  adamw_lr: 2.0e-3
  adamw_wd: 1.0e-2
  grad_clip: 0.0

  # ROUTING: first k blocks use Muon; others AdamW
  apply_layers: first_k
  first_k_blocks: 3

train:
  epochs: 40

log:
  log_interval: 50
  eval_interval: 1
  csv_path: results/metrics.csv
  svd_interval: 1000
  svd_layers:
    - backbone.blocks.0.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.1.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.2.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.3.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.4.edge_wise.so2_conv_1.fc_m0.weight
    - backbone.blocks.5.edge_wise.so2_conv_1.fc_m0.weight

checkpoint:
  save_dir: results/checkpoints_muon_firstk
  monitor: val_mae
  mode: min
