# Muon ablation applying Muon only to the first K message blocks
seed: 42
experiment_name: omat24_muon_firstk
task: omat24

dataset:
  root: data/rattled-300-subsampled
  target_key: energy_corrected_mp2020
  normalize_per_atom: true
  batch_size: 32
  num_workers: 0
  pin_memory: true
  radius: 6.0
  max_neighbors: 32
  split_fraction:
    train: 0.8
    val: 0.1
    test: 0.1
  max_samples: 20000
  split_seed: 1234

model:
  name: gemnet_oc_v2
  hidden_dim: 256
  depth: 6

train:
  epochs: 40
  grad_accum: 1
  precision: 32

optim:
  use_muon: true
  apply_layers: first_n
  first_k_blocks: 2
  adamw_lr: 2.0e-3
  adamw_wd: 0.01
  grad_clip: 1.0
  muon_lr: 2.0e-3
  muon_wd: 0.0
  muon_eps: 1.0e-8
  muon_momentum: 0.9
  ortho: true

log:
  backend: wandb
  project: muon-fairchem
  entity: null
  tags: ["muon", "first-k", "ablation"]
  log_interval: 50
  eval_interval: 1
  svd_interval: 1000
  svd_layers:
    - "backbone.interaction_blocks.4.mlp.0.weight"
    - "backbone.interaction_blocks.5.mlp.0.weight"

checkpoint:
  save_dir: results/checkpoints_muon_firstk
  monitor: val/mae
  mode: min
