experiment_name: omat24_muon_firstk_k1
seed: 42

dataset:
  root: data/rattled-300-subsampled
  target_key: energy_corrected_mp2020
  normalize_per_atom: true
  batch_size: 32
  num_workers: 0
  pin_memory: true
  radius: 6.0
  max_neighbors: 32
  split_fraction:
    train: 0.8
    val: 0.1
    test: 0.1
  max_samples: 20000
  split_seed: 1234

model:
  name: gemnet_oc_v2
  hidden_dim: 256
  depth: 6
  cutoff: 6.0
  max_neighbors: 32
  reduce: mean

train:
  epochs: 40
  grad_accum: 1
  precision: 32

optim:
  use_muon: true
  muon_lr: 0.002
  muon_wd: 0.0
  muon_eps: 1.0e-8
  muon_momentum: 0.9
  ortho: true
  adamw_lr: 0.002
  adamw_wd: 0.01
  grad_clip: 1.0
  apply_layers: first_k
  first_k_blocks: 1

log:
  log_interval: 50
  eval_interval: 1
  csv_path: results/metrics_muon_firstk_k1.csv
  svd_interval: 0

checkpoint:
  save_dir: results/checkpoints_muon_firstk_k1
  monitor: val_mae
  mode: min
